### ISSUE TITLE
Kali Persistance Issue

### ISSUE THREAD

**Issue by sha1024zz** [kasmtech/workspaces-issues#111] opened 2022-01-21 09:58 UTC
I am unable to get kali to work with persistence enabled.  It creates the folder structure but when i go to re-launch kali in kasm it displays connecting and goes into a loop.

Any help would be greatly appreciated.

Ubuntu persistence works no problem..

many thanks

**Comment by mmcclaskey** [comment] 2022-01-21 10:58
Can you share what you have configured in the image setting in both ubuntu and kali for the persistent profile path setting?

Each image should have a different location, so I want to validate that first, before asking to collect more debug information.

**Comment by sha1024zz** [comment] 2022-01-21 11:10
kali
persistent profile path setting
/data/profiles/{username}

i then deleted the profile and tried it with ubuntu which worked.
/data/profiles/{username}

**Comment by mmcclaskey** [comment] 2022-01-21 11:18
Each image needs a different path, because there are things in your home path that the OS and the software in the OS uses. So Kali and Ubuntu won't be the same and that will cause all kinds of issues. So, I would recommend something like.

/data/profiles/ubuntu/{username}
/data/profiles/kali/{username}

To share data between the two desktop environments, you can use volume mapping to share a location on the host, such as /data/org_share to the inside of user containers at /shares/org_share.
https://kasmweb.com/docs/latest/how_to/volume_mapping.html#volume-mapping-config

**Comment by sha1024zz** [comment] 2022-01-21 11:26
thanks
I totally agree - i deleted the kali profile folder before i tried it with ubuntu (it was a test to see if persistence works).  I have also tried different paths.  

If someone could try to reproduce then i will know if it is a config issue my side or it is something else.

**Comment by mmcclaskey** [comment] 2022-01-21 12:25
This is actually a known issue, duplicate of #106

**Comment by sha1024zz** [comment] 2022-01-21 13:00
Thanks you so much - not sure how i missed that.
Issue resolved.

**Closed as completed** 2022-01-21 13:03 UTC
Labels: duplicate
