### ISSUE TITLE
Kali Persistant profile

### ISSUE THREAD

**Issue by MrAshRhodes** [kasmtech/workspaces-issues#184] opened 2022-03-31 10:59 UTC
Using persistant profile stops kali from loading.

if i use reset or disabled kali will load.
As soon as i enable it kali doesnt load and just hangs.
Im noticing the following error in the log at the same time.

`Error trying to prune uneeded Docker image id (sha256:cba7a0fb018cfeb09bff43a11f980e649e10e0a1d0f4ffe40ab85e5e4c45efc0) with tags ([]) : 409 Client Error for http+docker://localhost/v1.41/images/sha256:cba7a0fb018cfeb09bff43a11f980e649e10e0a1d0f4ffe40ab85e5e4c45efc0?force=False&noprune=False: Conflict ("conflict: unable to delete cba7a0fb018c (must be forced) - image is being used by stopped container 78e6bbc3e336")`

**Comment by mmcclaskey** [comment] 2022-03-31 19:03
Did you by chance use another image with persistent profiles configured to use the same location prior to using Kali? Since Kali, Ubuntu, and CentOS (current core images) are all slightly different, you can't use the same persistent profile location between them. You could have multiple Kasm Images defined that use the same Docker image and have the same profile location.

I did test Kali with persistent profiles using kasmweb/core-kali-rolling:1.10.0-rolling and kasmweb/core-kali-rolling:1.10.0 images without issue on a fresh install.

**Comment by MrAshRhodes** [comment] 2022-04-01 07:23
On all my profile paths i following the following naming convention

`/mnt/kasm_share/persistant_profiles/kasm_$APPNAME/{username}`

What i have done is remove all the persistance profile folders and have them be recreated.

Initial launch of kali worked. i deleted the session... went back to Kali and got the same error.

In the logs i got the same message, but i noticed the kasmweb/core-ubuntu-bionic:1.10.0 tag... ive not launched that image at all. 

`Error trying to prune uneeded Docker image id (sha256:a4ade4116ad65a6e1c852d9c3376369901755c408baac343460fb2648c15d993) with tags (['kasmweb/core-ubuntu-bionic:1.10.0']) : 409 Client Error for http+docker://localhost/v1.41/images/sha256:a4ade4116ad65a6e1c852d9c3376369901755c408baac343460fb2648c15d993?force=False&noprune=False: Conflict ("conflict: unable to delete a4ade4116ad6 (cannot be forced) - image has dependent child images")`

edit:
docker command kali is constantly in a restarting state.
`root@localhost:~# docker container ls
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS                          PORTS                                           NAMES
c122313030e0   kasmweb/core-kali-rolling:1.10.0   "/dockerstartup/kasm…"   3 minutes ago   Restarting (1) 58 seconds ago                                                   mystifying_poitras`

Non Kali based images use persistant profile correctly

**Comment by mmcclaskey** [comment] 2022-04-04 11:50
For the prune error, Kasm continuously looks for docker images with a label that indicates that they are Kasm Workspace images and automatically removes them if they are not defined as a Kasm Image. This automatic pruning happens because, by default, Kasm updates the images. So if you changed the images to point to our rolling tagged images, your installation would update the images automatically every night with the new builds and it would prune the old images.

It seems that you have manually pulled that core image down to that system, but that image is not defined as a Kasm image, so Workspaces is trying to prune it. For a production environment, it is recommended to never build or manually pull things directly on the server, let Kasm fully manage things. If this is non-production system, then disable auto pruning so that you are not fighting with Kasm's auto pruning. IT WILL interfere with building images locally if you don't disable it. Go to Agents, click Edit on the agent, and disable auto pruning.

For your Kali issue, I was not able to duplicate. Please create a Kali session with the profile enabled and from the server output the logs of the container so we can see why it crashes...

```
sudo docker ps -a
# find the id of the container, it may not be running, so be sure to use -a
sudo docker logs abc123 > logs.txt
# where abc123 is the container id
```

**Comment by MrAshRhodes** [comment] 2022-04-04 12:16
I thought the pruning thing would be related.. i guess not, not urgent on that part. Ill remove the images causing that error. i was only messing around with them anyway.

Here's the attached logs. Seems to be in a constant restart
[kasm-kali-logs.txt](https://github.com/kasmtech/workspaces-issues/files/8409577/kasm-kali-logs.txt)

**Comment by mmcclaskey** [comment] 2022-04-06 15:41
Well that was unfortunately a little unhelpful. Could you please enable verbose startup logging inside the container by adding an environmental variable to the image settings. Admin -> Images -> Click the 3 dot icon next to the Kali image and select Edit. In the "Docker Run Config Override" section add the following...

`{ "environment": { "KASM_DEBUG": "1" }}`

Click Submit to save the changes to the image and launch a new instance. Please perform the same commands to get the logs from this instance, they should contain a lot more detail.

**Comment by MrAshRhodes** [comment] 2022-04-07 07:23
This has a lot more detail. i see an error relating to audio?

[kali.txt](https://github.com/kasmtech/workspaces-issues/files/8440531/kali.txt)

**Comment by mmcclaskey** [comment] 2022-04-07 10:50
Are you by chance using an NFS share or other remote file system to store the profiles on. There is a known bug, it has been fixed on the tip of develop but is not yet released. This affects Kali and Ubuntu 20.04 images. You can test our develop release, just be warned that it has not been tested nor intended to be used in Workspaces 1.10.0, but will likely work fine..

kasmweb/core-kali-rolling:develop

**Comment by MrAshRhodes** [comment] 2022-04-07 11:07
This has worked perfectly with the "develop" image.
its all running locally, no shares... Im ok with the develop image, ill be ok until the fix is released..

Thanks for your help and patience

**Comment by j-travis** [comment] 2022-04-11 08:35
I believe the original issue is a duplicate of https://github.com/kasmtech/workspaces-issues/issues/106. We've resolved the original issue in the `develop` images, which is why they work.

**Closed as completed by j-travis** 2022-04-11 08:35 UTC
Labels: duplicate
