### ISSUE TITLE
Stuck at a "Creating a secure connection..." screen

### ISSUE THREAD

**Issue by saddayyy** [kasmtech/workspaces-issues#140] opened 2022-02-01 16:38 UTC
When loading up any Kasm session, Kasm gets stuck on a "Creating a secure connection..." screen and then 2 minutes later goes to the admin panel. Please help!
Here are some logs:
Proxy Container - https://www.toptal.com/developers/hastebin/eyosojekaq.yaml
API - https://www.toptal.com/developers/hastebin/bayuxawazo.yaml

Let me know if you need any more information.

**Comment by mmcclaskey** [comment] 2022-02-01 17:20
@saddayyy, some of the containers need to be able to talk to each other using the public IP address that the user came in on. So lets say your pubic ip of the Kasm server is 123.123.123.123 and you navigate to https://123.123.123.123 to access it, the containers need to also be able to talk to 123.123.123.123 and sometimes that is blocked, because you are using a cloud provider where you need either allow 0.0.0.0:443 inbound or at least you need to allow 123.123.123.123:443 inbound. 

You can get around this a different way, by instructing Kasm to talk to itself via the private IP address of the server instead of the IP address that the client is using the access the server. In admin dashboard, go to Zones. In Zones click edit on the default zone. The change the "Upstream Auth Address" to the private IP address of your server and hit submit at the bottom.

**Comment by bmccraw86** [comment] 2022-02-09 13:40
I'm having the same issue. I tried changing the settings above, but it didn't seem to help. Below is my current default zone settings. I've tried both my proxy URL and my localhost URL, but both seem to have the same reaction.

![image](https://user-images.githubusercontent.com/6360872/153210400-dc32ba22-aea7-4432-86f7-30bed88b8e4f.png)

I launch the workspace, the docker container spins up and my browser attempts a secure connection through:

`https://{proxy-domain}/desktop/3a4972b8-4ce1-4e4e-b0a4-33ca143bc1af/vnc/vnc.html?video_quality=2&enable_webp=false&idle_disconnect=20&password=&autoconnect=1&path=desktop/3a4972b8-4ce1-4e4e-b0a4-33ca143bc1af/vnc/websockify&cursor=true&resize=remote&clipboard_up=true&clipboard_down=true&clipboard_seamless=true&toggle_control_panel=false`


The request eventually times out and I see this in the logs:
![image](https://user-images.githubusercontent.com/6360872/153211182-1fcf9f5a-d5b6-44e7-b348-41faa6fa1b04.png)

If I look at the kasm_proxy logs, I see the request to `/vnc/vnc.html`, but it gets a HTTP 499 return code. Not sure where to look past this.

As noted before, I'm running behind a proxy and on my host, port 443 was taken, so I'm running on port 8888, which I instructed Kasm about upon setup through the `-L ` flag.

**Comment by mmcclaskey** [comment] 2022-02-14 12:33
These symptoms are due to the API service not being able to talk to kasm_proxy in the same way that your clients do. Kasm_proxy is an nginx container that is part of the Kasm Workspaces stack. 

This presents a problem in many Cloud providers. For example, in AWS lets say your public IP address was 123.123.123.123, you would have to go into the security group assigned to that VM and allow 123.123.123.123 to accept traffic from 123.123.123.123/32 on port 443. This does not apply if you are already allowing 0.0.0.0/0 on 443 inbound. 

Please validate by connecting to the server that has Kasm Workspaces installed on it and curl the same exact URL users access the server with.

curl -v -k https://<domain-name-or-public-ip>

Make sure to use the domain name if users access by domain name. Please post the results.

**Comment by btmaple** [comment] 2022-02-15 19:35
I am having the same problem. Here is the output from the command above:

root@wb:/opt/kasm/bin# curl -v -k https://spaces.wpdevdaemon.com
*   Trying 104.21.25.69:443...
* TCP_NODELAY set
* Connected to spaces.wpdevdaemon.com (104.21.25.69) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: May 27 00:00:00 2021 GMT
*  expire date: May 26 23:59:59 2022 GMT
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55cb3c342e30)
> GET / HTTP/2
> Host: spaces.wpdevdaemon.com
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Tue, 15 Feb 2022 19:34:06 GMT
< content-type: text/html
< last-modified: Mon, 14 Feb 2022 23:43:09 GMT
< expires: Tue, 15 Feb 2022 23:34:06 GMT
< cache-control: max-age=14400
< cache-control: private
< x-served-by: spaces.wpdevdaemon.com
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=lGju1dN%2FHI9sVRelHsL8i8PBFpjMGjSddkhmJhsp%2BC6K17sa9sB8O9c8wQ%2BnQVt3WwI1%2FBgMFX%2Fgx1Iz%2BOmhzAEbO8C0TUj6FBYDaTz3fqNQcNO3fqbJKRpSUm4ZSw9CzpVBzK1cEDA9"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 6de0f8c31ffa27f4-SLC
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
* Connection #0 to host spaces.wpdevdaemon.com left intact
<!doctype html> <html lang=en> <head> <meta charset=utf-8> <meta http-equiv=X-UA-Compatible content="IE=edge"> <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,shrink-to-fit=no"> <link id=favicon rel="shortcut icon" href=""> <title></title> <link href="index.fonts.css?4fb3041fc0ff22073775" rel="stylesheet"><link href="index.styles.css?4fb3041fc0ff22073775" rel="stylesheet"></head> <body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden"> <div id=root></div> <script type="text/javascript" src="index.bundle.js?4fb3041fc0ffroot@wb:/opt/kasm/bin#

**Comment by mmcclaskey** [comment] 2022-02-16 12:42
@bmccraw86 , you stated that you installed with the -L option to change the port, however, the request in the log provided does not show a port number, which would mean it is using 443. Also the screenshot of the zone settings shows 443 as well. I would suggest going through the docs again, the part that covers changing the port number AFTER installation, to ensure everything looks like it is on 8888.

**Comment by mmcclaskey** [comment] 2022-02-16 12:47
@btmaple your curl looks good, but it does show me that you are using CloudFlare, nothing wrong with that but an important note for now. @saddayyy, if your curl looks good as well, then this applies to you as well.

When you try to establish a connection to a desktop, can you provide the API and proxy logs from Kasm? You may have to sanitize sensitive information. 

`sudo docker logs -f --tail 30 kasm_api`
`sudo docker logs -f --tail 30 kasm_proxy`

The logs are also written to file at /opt/kasm/current/log

**Comment by bmccraw86** [comment] 2022-02-16 14:54
**FIXED**

I found my problem. I'll go over my setup, then point out where I messed up.

I installed with the `-L` option to override the port to `8888` as shown here:
`bash kasm_release/install.sh -L 8888`

This is the `docker ps` output after the install completed and everything was started:

```
2f9faf9a9036   kasmweb/nginx:latest              "/docker-entrypoint.…"   About an hour ago   Up About an hour             80/tcp, 0.0.0.0:8888->8888/tcp, :::8888->8888/tcp   kasm_proxy
c4d2ff1de9da   kasmweb/agent:1.10.0              "/bin/sh -c '/usr/bi…"   About an hour ago   Up About an hour             4444/tcp                                            kasm_agent
cc4cfbd4bf0c   kasmweb/share:1.10.0              "/bin/sh -c '/usr/bi…"   About an hour ago   Up About an hour             8182/tcp                                            kasm_share
9a11e24a105b   kasmweb/manager:1.10.0            "/bin/sh -c '/usr/bi…"   About an hour ago   Up About an hour             8181/tcp                                            kasm_manager
f8b8f5fa2abe   redis:5-alpine                    "docker-entrypoint.s…"   About an hour ago   Up About an hour             6379/tcp                                            kasm_redis
904dd69c19b6   kasmweb/api:1.10.0                "/bin/sh -c '/usr/bi…"   7 days ago          Up About an hour (healthy)   8080/tcp                                            kasm_api
05b9c4e89110   postgres:12-alpine                "docker-entrypoint.s…"   7 days ago          Up About an hour             5432/tcp                                            kasm_db
```

This made it possible to hit kasm on `localhost:8888` but I want to go through a Reverse Proxy to make it easier and expose kasm externally through Cloudflare.

To get this to work, you have to adjust your Zones within the Kasm admin by following this doc: 
https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones

As @mmcclaskey pointed out, if you read the documentation carefully, you'll get it right (I apparently skipped one step).

You must change two settings on your default zone...the **Upstream Auth Address** and the **Proxy Port**. For me, this meant setting `Upstream Auth address = localhost` and the `Proxy Port = 443`. 

What I missed the first time was changing the `Upstream Auth address`.

**Comment by quangld** [comment] 2022-02-20 04:22
> You must change two settings on your default zone...the **Upstream Auth Address** and the **Proxy Port**. For me, this meant setting `Upstream Auth address = localhost` and the `Proxy Port = 443`.

Thank! this fixed the problem for me too. I am running Kasm Workspace on port 8443, because nginx is used for my web app. So I use reverse proxy in nginx to redirect kasm subdomain traffic to 8443.
* I had tried everything (switching between public ip, private ip, subdomain name, 127.0.0.1 and port 8443 and 443)
-> For some reason beyond my understanding of proxy: "**localhost**" works!
which is really strange because 127.0.0.1 doesn't work!

**Closed as completed** 2022-04-11 09:23 UTC
