### ISSUE TITLE
Help - securing Kasm

### ISSUE THREAD

**Issue by charlespick** [kasmtech/workspaces-issues#340] opened 2023-03-15 02:32 UTC
I want Kasm to log off users if there is no input, even if a RDP connection is still open. I just did some controlled testing to confirm that the auto logout is not working right now. Is this a configuration problem or a bug? 

I opened Kasm in a new VM and connected to an RDP workspace, then locked the VM and came back 2 and a half hours later and the Kasm was still connected. This a problem because I will admittedly, sometimes walk away and forget to lock.

**Comment by rickkoliser** [comment] 2023-03-15 15:56
I'd like to get some more information. What version of Kasm Workspaces are you running. When you say you are connecting to RDP workspaces, is that using our new feature released with Kasm Workspaces 1.12.0 for defining and connecting to RDP endpoints (https://kasmweb.com/docs/latest/how_to/fixed_infrastructure.html), or are you connecting to RDP through a Linux workspace such as the Remmina workspace. 

Just to make sure I am clear on your intended behavior when you state you want Kasm to log off users you mean that you want Kasm users to be completely logged out of Kasm Workspaces and returned to the login screen, not that you want users to be redirected back to the dashboard and simply disconnected from any existing Kasm sessions? 

Kasm has a number of settings that are related to session timing. Please take a look at this documentation: https://kasmweb.com/docs/latest/guide/groups/group_settings.html#session-time-limits. Not all of these settings will be configured on your installation. Can you tell me what these settings are set to for the user you are testing? You can find the settings that apply to a particular user by going to the admin page and selecting 'Users' click on the three dot menu next to the user you want to view and select 'View' scroll down to the section 'Resultant Group Settings' and you will be able to find each of the settings defined in the documentation above.

The information here should help me to get a better understanding of what is happening on your system and how we can get the behavior you desire.

Thank you,
Rick

**Comment by charlespick** [comment] 2023-03-15 22:24
I am running Kasm 1.12.0.d4fd8a. I am using the new "fixed infrastructure" RDP connections with a defined server and workspace in Kasm. I want Kasm workspaces entirely to log out after inactivity so that if a stranger were to walk up to the computer after the specified period of time, they would not be able to continue the RDP session, launch a new RDP session, launch any container workspaces, or because this is an admin account, change any kasm settings. The idle_disconnect is set to 20 for my user account.

**Comment by rickkoliser** [comment] 2023-03-17 13:14
Good morning,
    Sorry I did not get back to you yesterday, I was testing out a number of scenarios to try and reproduce the issue you are seeing. I was able to reproduce what appears to be the issue you are experiencing yesterday running my browser inside a VM, I will continue looking into it and get back to you with more information early next week.

**Comment by rickkoliser** [comment] 2023-03-22 15:59
Good morning,
    Can you try our developer preview https://kasmweb.com/docs/latest/developers/builds.html, we have made some improvements in timeouts for the next release and those are in our developer preview builds. We don't recommend using our developer preview builds in production environments since they are based on our development branch which changes daily, however it will give a good indication if we have fixed the issue you are running into for our next production release. I tested your scenario using the developer preview build and Kasm was logging out successfully for me.

**Comment by charlespick** [comment] 2023-03-22 18:58
I can try to find time to spin up a new instance in the next week. Any idea when this will move to release stage?

**Comment by rickkoliser** [comment] 2023-03-23 14:21
We anticipate releasing the next version of Kasm Workspaces sometime in April. Please let me know how your testing goes.

**Comment by charlespick** [comment] 2023-03-24 03:23
Looks like it's working! I'm seeing this when I return to the VM after a while. Note I have not setup ADFS or groups or anything for this installation. 
<img width="1800" alt="Screenshot 2023-03-23 at 8 21 33 PM" src="https://user-images.githubusercontent.com/17918019/227416158-d9ddc99b-820f-4d63-8e2a-a67f12d9c7e7.png">

**Comment by rickkoliser** [comment] 2023-03-24 13:14
I'm happy to hear that the developer preview build is working for you. If you run into further issues when setting up your groups and ADFS please let me know.

**Closed as completed** 2023-03-30 01:20 UTC
