### ISSUE TITLE
Google Artifact Registry unauthorized authentication failed.

### ISSUE THREAD

**Issue by shanehughes1990** [kasmtech/workspaces-issues#400] opened 2023-05-30 18:41 UTC
If you follow the google docs on how to authenticate to artifact registry via username/password it tells you you need a service account
https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key

That is the google doc for it, says username is to be either `_json_key` or `_json_key_base64`
If I run the command it tells me to just on my docker terminal (not related to kasm), the login works I can pull me image no problem so I know the google IAM for that service account is setup correctly.

When I apply that to a kasm workspace in the workspace settings for docker registry I get the following error in logs
![image](https://github.com/kasmtech/workspaces-issues/assets/31993465/3c3473ec-4fe0-4992-b41f-8a0566141e86)

And the workspace settings itself
![image](https://github.com/kasmtech/workspaces-issues/assets/31993465/ae2223e6-875c-445d-aa2f-bd72c96f6b32)

Docker registry password is I verified several times to be correct the base64 encoded string of the json service account key google gives you.

I've tried it as the fully qualified URL with the https:// Infront and without both result in the same log error.

If I change the view in logging to debug level we can see a little more info but not enough to help me troubleshoot further

![image](https://github.com/kasmtech/workspaces-issues/assets/31993465/5e6d3265-184e-4be2-9e34-1752844aef44)

**Comment by j-travis** [comment] 2023-05-30 18:53
Hi, thanks for reporting.
Unfortunately you won't be able to proceed much farther at this point.  The issue is caused because the field in our DB is only a maximum of 48 characters, thus your long b64 string is getting truncated.

We will update this ticket when a fix becomes available

**Comment by shanehughes1990** [comment] 2023-05-31 14:37
Thank you for letting me know, I will keep an eye on this ultimately I would like to use artifact registry as that is where everything else is in our setup, but we do have digital ocean working so I will continue to use theirs until this get's fixed.

**Comment by Ian-Kasmweb** [comment] 2023-08-02 20:48
The fix for this has been made and is available via the [developer preview](https://kasmweb.com/docs/develop/developers/builds.html).
The upcoming 1.14.0 release will have this fixed as well.

**Closed as completed** 2023-08-02 20:52 UTC
